name: tox
on: [push, pull_request]
jobs:
  tox:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: |
            tox.ini
            setup.py
      - run: pip install tox
      - if: matrix.python == '3.7'
        run: TOXENV=py37 tox
      - if: matrix.python == '3.8'
        run: TOXENV=py38 tox
      - if: matrix.python == '3.9'
        run: TOXENV=py39 tox
      - if: matrix.python == '3.10'
        run: TOXENV=py310 tox
      - if: matrix.python == '3.11'
        run: TOXENV=py311 tox
      - if: matrix.python == '3.12'
        run: TOXENV=py312 tox
